# Generated by Django 5.2.6 on 2025-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingChildReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('last_area', models.CharField(max_length=200)),
                ('moles', models.CharField(max_length=200)),
                ('dress_color', models.CharField(max_length=50)),
                ('child_photo', models.ImageField(upload_to='child_photos/')),
                ('aadhaar_photo', models.ImageField(upload_to='aadhaar_photos/')),
                ('fir_copy', models.FileField(blank=True, null=True, upload_to='fir_copies/')),
                ('reporter_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
