# Generated by Django 5.2.6 on 2025-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingchildreport',
            name='status',
            field=models.CharField(choices=[('missing', 'Missing'), ('found', 'Found')], default='missing', max_length=10),
        ),
    ]
