# Generated by Django 5.2.6 on 2025-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild', '0002_missingchildreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_uploads/')),
                ('uploader_name', models.CharField(max_length=100)),
                ('uploader_contact', models.CharField(max_length=100)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
