# Generated by Django 5.2.6 on 2025-10-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild', '0003_reportupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingchildreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
