# Generated by Django 5.2.6 on 2025-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild', '0004_alter_missingchildreport_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('matched_child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
