# Generated by Django 5.2.6 on 2025-10-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingchild', '0005_uploadedphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedPhoto',
        ),
        migrations.AddField(
            model_name='reportupload',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportupload',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportupload',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportupload',
            name='matched_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missingchild.missingchildreport'),
        ),
        migrations.AddField(
            model_name='reportupload',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reportupload',
            name='uploader_contact',
            field=models.CharField(max_length=20),
        ),
    ]
